// This is a list of message variation types that should include all responses, "error" messages, etc.
module.exports = {
	ALREADY_WORKING: 'alreadyworking',
	ARREST_CURRENT_SUSPECT: 'arrestcurrentsuspect',
	ARREST_SELF: 'arrestself',
	ARREST_SHERIFF: 'arrestsheriff',
	ARREST_WHO: 'arrestwho',
	BAD_NUMBER: 'badnumber',
	COULD_NOT_UNDERSTAND: 'couldnotunderstand',
	CURRENT_SUSPECT: 'currentsuspect',
	EMPTY_JAIL: 'emptyjail',
	EQUAL_SENTENCE: 'equalsentence',
	GO_TO_JAIL: 'gotojail',
	LONGER_SENTENCE: 'longersentence',
	MEOW_RESPONSE: 'meowresponse',
	NEGATIVE_DICE: 'negativedice',
	NO_CHARGE: 'nocharge',
	NO_CHARGE_YET: 'nochargeyet',
	NO_CRIMES: 'nocrimes',
	NOT_A_CRIME: 'notacrime',
	NOT_A_PERSON: 'notaperson',
	ON_THE_BEAT: 'onthebeat',
	ONE_SIDE_DIE: 'onesidedie',
	ORIGINAL_ACCUSER: 'originalaccuser',
	REPRIMAND: 'reprimand',
	SENTENCE_SERVED: 'sentenceserved',
	SHORTER_SENTENCE: 'shortersentence',
	SUCCESSFUL_ARREST: 'successfularrest',
	WELCOME: 'welcome',
	ZERO_DICE: 'zerodice'
}